events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        # Define a variable to check if the app is down
        set $app_status "up";

        if (-f /etc/nginx/app-down) {
            set $app_status "down";
        }

        # Serve assets from the app if it is up, fallback to Nginx if down
        location ~* ^/(stylesheets|javascripts|assets)/ {
            if ($app_status = "up") {
                proxy_pass http://flood-app:3001;
                # these headers cant be set in a conditinal apparently. maybe to
                # investigate
                # proxy_set_header Host $host;
                # proxy_set_header X-Real-IP $remote_addr;
                break;
            }

            root /usr/share/nginx/html;
            autoindex off;
            add_header Cache-Control "public, max-age=86400";
        }

        # Default route (Proxy to App)
        location / {
            proxy_pass http://flood-app:3001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # Redirect to maintenance page if app is down
            if (-f /etc/nginx/app-down) {
                return 302 $scheme://$host:8081/maintenance.html;
            }
        }

        # Maintenance page
        location = /maintenance.html {
            root /usr/share/nginx/html;
            try_files /service-down.html =404;
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
            add_header Pragma "no-cache";
            add_header Expires 0;
        }
    }
}
